### ISSUE TITLE
'(slice(None, None, None), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])' is an invalid key 

### ISSUE THREAD

**Issue by mossadhelali** [thomas-young-2013/automl-toolkit#20]
**Describe the bug**
Thanks for the library. When using `model.predict()`, sometimes I get the following Exception:
```
Traceback (most recent call last):
  File "evaluate_on_dataset.py", line 51, in test_volcano
    score = f1_score(ytest, model.predict(test_data), average='macro')
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/estimators.py", line 42, in predict
    return super().predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/base_estimator.py", line 98, in predict
    return self._ml_engine.predict(X)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/automl.py", line 186, in predict
    return self.solver.predict(test_data)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/blocks/abstract_block.py", line 143, in predict
    pred = self._predict(test_data)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/blocks/abstract_block.py", line 165, in _predict
    test_data_node = construct_node(test_data_node, best_op_list)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/components/feature_engineering/parse.py", line 99, in construct_node
    data_node = tran_dict[stage].operate(data_node)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/components/feature_engineering/transformations/base_transformer.py", line 153, in dec
    _X = func(*args)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/components/feature_engineering/transformations/rescaler/robust.py", line 22, in operate
    X_new = X[:, target_fields]
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/pandas/core/frame.py", line 2917, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2602, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 110, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])' is an invalid key
```

I noticed this happends when input data variables are pandas.DataFrame() objects. 

**Library Versions**
Library Versions
mindware==0.5.0
openbox==0.7.16
pandas==0.24.0
numpy==1.21.5
scikit-learn==1.0.2
scikit-optimize==0.9.0
torch==1.10.1+cpu

**Comment by salty-fish-97** [comment]
Thanks for the issue! 

The data type for estimators (e.g., the Classifier) should be numpy.Array. Or else, it may lead to some unpredictable bugs as the one in the issue. To convert the DataFrame objects into numpy.Array, we suggest using the DataManager or manually applying essential transformations (e.g., label encoding).

The data input can be pandas.DataFrame objects when passing into the DataManager. By using `preprocess_fit` and `preprocess_transform`, the data in the returned data node will be numpy.Array objects. For example,
```
# xtrain, ytrain are pandas.DataFrame objects
dm = DataManager(xtrain, ytrain)

train_data = dm.get_data_node(xtrain, ytrain)
train_data = dm.preprocess_fit(train_data)
test_data = dm.get_data_node(xtest, ytest)
test_data = dm.preprocess_transform(test_data)
```

To avoid these bugs, please make sure that, when passing the data into the estimators, the data type in the DataNode should be numpy.Array.

**Comment by mossadhelali** [comment]
Thanks, @salty-fish-97  . Numpy arrays worked!
