### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory with pickle files while fitting

### ISSUE THREAD

**Issue by mossadhelali** [thomas-young-2013/automl-toolkit#21]
**Describe the bug**
Hi, sometimes I get the following error while fitting a dataset. 

```
Traceback (most recent call last):
  File "evaluate_on_dataset.py", line 53, in test_volcano
    model.fit(train_data)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/estimators.py", line 27, in fit
    super().fit(data, **kwargs)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/base_estimator.py", line 92, in fit
    self._ml_engine.fit(data, **kwargs)
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/automl.py", line 176, in fit
    self.solver.fit_ensemble()
  File "/dccstor/abdelai1/anaconda2/envs/volcano/lib/python3.7/site-packages/mindware/blocks/abstract_block.py", line 128, in fit_ensemble
    with open(config_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/mindware-1643125097.4067643/1643126552.6057668_topk_config.pkl'
``` 
In my setting, I configured the `output_dir` to be `tmp` (in the local directory of the script). This happens when `ensemble_method` is not None, but not always. 

Thanks for the effort

**Comment by salty-fish-97** [comment]
Thanks for the issue!

It seems that the file that contains the locations of the best stored models is missing. Would you help check if there is another file with a name "*\*.topk_config.pkl*" under the same directory? And would you provide the parameter settings for the estimator you use when fitting the dataset. This may help up locate the bug and find a solution. Thanks.

**Comment by mossadhelali** [comment]
Thanks for your reply, @salty-fish-97  . 
There was no `*.topk_config.pk` file in `output_dir`. 
Here is the output that I get before the exception happens:
```
[INFO] [2022-01-25 11:57:35,445] [Soln-ml: default_dataset_name] Time elapsed!
[INFO] [2022-01-25 11:57:35,446] [Soln-ml: default_dataset_name] ==================================================
[INFO] [2022-01-25 11:57:35,446] [Soln-ml: default_dataset_name] Node index: 0
[INFO] [2022-01-25 11:57:35,447] [Soln-ml: default_dataset_name] Best_algo_perf:  -inf
[INFO] [2022-01-25 11:57:35,447] [Soln-ml: default_dataset_name] Best_algo_id:    None
[INFO] [2022-01-25 11:57:35,447] [Soln-ml: default_dataset_name] Arm candidates:  ['liblinear_svc', 'random_forest', 'lda', 'extra_trees', 'adaboost', 'logistic_regression', 'libsvm_svc', 'qda', 'k_nearest_neighbors', 'gradient_boosting', 'lightgbm']
[INFO] [2022-01-25 11:57:35,447] [Soln-ml: default_dataset_name] Best val scores: [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]
[INFO] [2022-01-25 11:57:35,447] [Soln-ml: default_dataset_name] ==================================================
```
Does that mean that Mindware couldn't find a viable solution?

Here are the parameters I am specifying:
```
model = Classifier(time_limit=3300,
                              metric='f1',
                              n_jobs=10,
                              output_dir="tmp/",
                              )
```
Thanks in advance.

**Comment by 0mu2004** [comment]
Hi @thomas-young-2013 , I want to work on this issue. Is it still open?
